-------------------------------------------------------
--  DDL for Table GC_T_CLOSED_POSITIONS
--------------------------------------------------------

CREATE TABLE "GC_T_CLOSED_POSITIONS" 
   (	"ACCOUNT" VARCHAR2(20 BYTE), 
	"ACT" VARCHAR2(1 BYTE), 
	"TICKET" NUMBER(10), 
	"INSTRUMENT" VARCHAR2(80 BYTE), 
	"LOT" NUMBER(8,2), 
	"BS" VARCHAR2(1 BYTE), 
	"OPEN" NUMBER(16,6), 
	"OPENDATE" DATE, 
	"CLOSE" NUMBER(16,6), 
	"CLOSEDATE" DATE,
	"LOTPL" NUMBER(8,2), 
	"COM" NUMBER(8,2), 
	"SWAP" NUMBER(8,2), 
	"FUTROLLADJ" NUMBER(8,2), 
	"NETPL" NUMBER(8,2), 
	"REASON" VARCHAR2(1 BYTE), 
	"OPNCHANGE" NUMBER(8,2), 
   	"USER" VARCHAR2(80 BYTE), 
	"CLCHARGE" NUMBER(8,2), 
   	"OPENEDBY" VARCHAR2(80 BYTE), 
   	"CLOSEDBY" VARCHAR2(80 BYTE), 
	"TRADEID" NUMBER(10), 
   	"COMMENT" VARCHAR2(80 BYTE), 
	"TRADEOPENDATE" DATE
   ) ;
