CREATE OR REPLACE FORCE VIEW "VSU"."GC_V_CLOSED_POSITIONS" ("PRODUCT", "BETACTION", "BET#", "BETOPEN", "BETCLOSE", "PROFITBRUTTO", "COMSWAP", "PROFIT", "TIMEOPEN", "TIMECLOSE") AS 
  SELECT 
REGEXP_SUBSTR (INSTRUMENT, '(\S*)')
,BS
,LOT
,OPEN
,CLOSE
,NETPL-COM-SWAP
,COM+SWAP
,NETPL
,OPENDATE
,CLOSEDATE
FROM 
GC_T_CLOSED_POSITIONS
order by CLOSEDATE;
